### ISSUE TITLE
Itálico

### ISSUE THREAD

**Issue by anacastrosalgado** [anacastrosalgado/DLP#21]
Em etimologia, ao atribuir uma ref, usar itálico.

**Comment by ambs** [comment]
Acho que acabei de adicionar o itálico.
Vê se fica assim ou se queres mudar.

**Comment by anacastrosalgado** [comment]
Reabriste?

**Comment by ambs** [comment]
Sim, porque mexi em alguma coisa.
Vê se está bem como está.
